



language: python

python:
  - "2.7"

install:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install coveralls


script:
  - pytest --cov=Questioner-api tests/

after_success:
  - coveralls





